### ISSUE TITLE
Is This Really a Working Project?

### ISSUE THREAD

**Issue by behiunforgiven** [arsanjani/url-shortener#1]
Hi, I cloned this project and ran it. but it seems this project is incomplete. 
How can we shorten a URL?
manually insert a URL in db?

**Comment by arsanjani** [comment]
Hi @behiunforgiven,
Have you followed the instructions on the [README.md](https://github.com/arsanjani/url-shortener/blob/main/README.md) file ? After creating tables, you need to identify your short link information in the `ShortLink` table. For example for having a custom link like `http://example.com/mylink` and redirecting it to `http://google.com` you need to insert a record like this:
```sql
INSERT INTO ShortLink (Token, IsPublish, OriginLink, CreateAdminID)
VALUES ('mylink',1,'http://google.com',1)
```
However, this project doesn't have any GUI. It just provides you with an API for that. You can build an interface above it based on your needs.
